//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sentiment_analysis_v3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sentiment_analysis_v3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icons8_emojis_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_emojis_64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rudimental_bold {
            get {
                object obj = ResourceManager.GetObject("rudimental_bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NBC Commissary has @CokeZero on fountain. It&apos;s little things like that that make my day.
        ///@cokezero vanilla is really good with fish tacos.
        ///just drinkin some @CokeZero and listening to @mtrench :) it&apos;s a typical night for me
        ///@CokeZero just incredible taste! it is hard to believe that Zero contains no sugar but it is totally true.
        ///@cokezero If this doesn&apos;t make you want a Vanilla Coke Zero I don&apos;t know what will. I should advertise for y&apos;all. :) http://t.co/5yNJnW0
        ///@MUpshaw33 Ooh! Rum and p&apos;ipple jui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tweets_data {
            get {
                return ResourceManager.GetString("tweets_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///O
        ///O
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///N
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///N
        ///P
        ///P
        ///O
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///N
        ///N
        ///N
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P
        ///P        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tweets_label {
            get {
                return ResourceManager.GetString("tweets_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to against,747,482
        ///yzl,2,1
        ///aww,10422,6404
        ///that,13477,18121
        ///bummer,1446,138
        ///shoulda,271,87
        ///got,33608,28189
        ///david,1159,1389
        ///carr,44,66
        ///third,457,391
        ///day,52111,56809
        ///d,4066,4809
        ///upset,2803,234
        ///cant,44300,19533
        ///updat,4770,4499
        ///facebook,2230,2630
        ///text,3161,2560
        ///might,4724,5008
        ///cri,7431,1196
        ///result,881,825
        ///school,13289,8017
        ///today,38361,30342
        ///also,4735,5707
        ///blah,1272,400
        ///dive,120,157
        ///mani,4750,4286
        ///time,31776,34599
        ///ball,1178,970
        ///manag,1348,1192
        ///save,1978,1800
        ///rest,2822,3100
        ///go,79318,593 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string word_count {
            get {
                return ResourceManager.GetString("word_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to against,47,44
        ///sad,1697,118
        ///apl,1,1
        ///friend,548,755
        ///miss,2465,666
        ///new,618,1195
        ///moon,37,72
        ///trailer,25,43
        ///omg,430,284
        ///alreadi,479,395
        ///o,372,369
        ///omgaga,1,0
        ///im,6119,5314
        ///soo,460,366
        ///gunna,26,29
        ///cri,442,76
        ///ive,873,766
        ///dentist,31,7
        ///sinc,298,267
        ///supos,2,0
        ///get,3266,3295
        ///crown,8,6
        ///put,272,370
        ///min,109,91
        ///think,1508,1862
        ///mi,21,20
        ///bf,47,21
        ///cheat,25,15
        ///t,183,180
        ///worri,162,266
        ///much,962,1278
        ///juusst,0,1
        ///chillin,22,32
        ///sunni,60,92
        ///work,2250,1506
        ///tomorrow,601,577
        ///tv,153,162
        ///tonight,524,468
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string word_count1 {
            get {
                return ResourceManager.GetString("word_count1", resourceCulture);
            }
        }
    }
}
